### ISSUE TITLE
Select Group 组件不支持多选

### ISSUE THREAD

**Issue by jaceyi** [UCloud-FE/react-components#100]
**Current behavior**
Select Group 组件传 multiple 参数会报错

**Expected behavior**
Describe what the behavior would be without the bug.

**To Reproduce**

**Minimal demo**
If the current behavior is a bug and you can reproduce with an example,
please provide a _MINIMAL DEMO_ of the problem via
https://codesandbox.io/ or similar (you can use this template as a starting point: https://codesandbox.io/s/wnnv1op5yw).

**Package version** x.y.z
Check whether this is still an issue in the most recent stable.

**Screenshots**

**Browser**
All browsers where this could be reproduced (and Operating System if relevant), please complete the following information:

*   OS: [e.g. MacOS]
*   Browser [e.g. chrome, safari]
*   Version [e.g. 22]

**Additional context**

**Comment by ZxBing0066** [comment]
Need more information
