### ISSUE TITLE
Radio button when checked and disabled  only shows state of checked(probably it should show state of disable)

### ISSUE THREAD

**Issue by yingyi-sun** [UCloud-FE/react-components#336]
![image](https://user-images.githubusercontent.com/66585499/129351735-5225c84b-f5cd-45c8-a62a-df9a417870be.png)
 the first radio is disabled, but at the same time, if the defaultValue of radio group is this item,  it will show state of checked; probably  state of disable will be better.

**Comment by ZxBing0066** [comment]
Duplicated: https://github.com/UCloud-FE/react-components/issues/137

Disabled and defaultChecked at the same time for a radio is unreal, our UX didn't consider that case.

When a radio is disabled and defaultChecked, the state can't reset when user change it to other options. We consider this as an unreal case.

-------------

Radio 中禁用和选中是互斥的，当选中其它选项后无法重置为该选项，遇到这种场景应该考虑下是否是交互出了问题。
