### ISSUE TITLE
AutoComplete组件onChange的使用

### ISSUE THREAD

**Issue by duheng1992** [UCloud-FE/react-components#350]
**Current behavior**
onChange可以触发search事件和选中下拉列表后的操作。

**Expected behavior**
search事件和选中下拉列表后的操作分别响应。

**question**
我这里使用的时候，option是自定义的一个显示：
```js
label: (
      <span
          style={{
              display: 'inline-block',
              maxWidth: '400px',
              height: '24px',
              whiteSpace: 'nowrap',
              textOverflow: 'ellipsis',
              overflow: 'hidden'
              ...
          }}
      >
          {item.ShortLink}
      </span>
  ),
  value: item
```
问题一：可以看到value是一个object，在点击选中一项后，在界面显示成了[object Object]，所以我不得不魔改样式，或者用value: item.ShortLink代替。请问还有更好的解决办法吗？处理这种value不是字符串的问题。
问题二：第二个问题应该和第一个有关系，点击选中一项如果不是触发onChange，而是触发另外一个什么事件，比如onSelected，这样就可以剥离出界面显示和state中实际的值了。我现在想要拿到整个object，但又不想在界面显示她，请问有改进的办法吗？

我目前的方法是在span上加onCLick来判断两种触发事件，请问是否有更好的办法？

**version**
"@ucloud-fe/react-components": "1.3.1"

**Browser**
chrome

**Comment by ZxBing0066** [comment]
autocomplete 的作用是输入，本质是一个带提示的输入框而不是选择器，你的场景应该是使用选择器而不是 AutoComplete
