### ISSUE TITLE
Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by UlyC** [UCloud-FE/react-components#83]
When I use ‘’formDecorator‘’ of ZForm to wrap “Slider“  component  up ，getted  the following error:
`Cannot read property 'toFixed' of undefined`·

**Comment by ZxBing0066** [comment]
When wrap controllers with controllerDecorator, controller must to be controlled, defaultValue is not used.
You can fix this by provide a initialValue like below.
```jsx
const ZSlider = controllerDecorator({
	initialValue: 0 // your default value
})(Slider);
```

I will fixed this in next patch version
