### ISSUE TITLE
Table component merge cell function

### ISSUE THREAD

**Issue by jaceyi** [UCloud-FE/react-components#84]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
加个单元格合并的功能吧😘😘😘😘

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by ZxBing0066** [comment]
描述都不写的吗，不写英文可以写中文😂

**Comment by jaceyi** [comment]
2333 手抖点击 close 了，现在写描述了🤣
