### ISSUE TITLE
Table handleOrder

### ISSUE THREAD

**Issue by heanxu** [UCloud-FE/react-components#92]
**Current behavior**
Describe how the bug manifests.
表排序的时候，点击了列的排序功能后无法恢复默认状态
具体见：https://github.com/UCloud-FE/react-components/blob/master/src/components/Table/Table.jsx#L354
order.state 为 none 时还是 "desc"

**Expected behavior**
Describe what the behavior would be without the bug.
点击时应该有降序/升序/默认状态

**To Reproduce**

1.  Go to Table
2.  Click on sort

**Minimal demo**
If the current behavior is a bug and you can reproduce with an example,
please provide a _MINIMAL DEMO_ of the problem via
https://codesandbox.io/ or similar (you can use this template as a starting point: https://codesandbox.io/s/wnnv1op5yw).

**Package version** x.y.z
Check whether this is still an issue in the most recent stable.

**Screenshots**

**Browser**
All browsers where this could be reproduced (and Operating System if relevant), please complete the following information:

*   OS: [e.g. MacOS]
*   Browser [e.g. chrome, safari]
*   Version [e.g. 22]

**Additional context**

**Comment by ZxBing0066** [comment]
组件的交互定义就是这样，可以商讨一下

**Comment by ZxBing0066** [comment]
和交互讨论后切换逻辑已经修改，下个版本发布
